services:
  laravel-p3:
    build:
      context: .
      dockerfile: Dockerfile-php
    container_name: laravel-p3
    restart: always
    volumes:
      - ./laravel:/var/www/html
    ports:
      - "8093:80"
    depends_on:
      - db-p3

  db-p3:
    image: mysql:8.0
    container_name: mysql-db-p3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: reparaya
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    volumes:
      - db_data_p3:/var/lib/mysql

  phpmyadmin-p3:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-p3
    restart: always
    ports:
      - "8094:80"
    environment:
      PMA_HOST: db-p3
      MYSQL_ROOT_PASSWORD: rootpass
    depends_on:
      - db-p3

volumes:
  db_data_p3: